services:
  web:
    build: .
    container_name: movieweb
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://movienight:movienight@db:5432/movienightdb
      - FLASK_ENV=development
<<<<<<< HEAD
      - SECRET_KEY=MicDaddy
=======
      - FLASK_APP=run.py
      - SECRET_KEY=dev-secret-key-change-me
    volumes:
      - .:/app
>>>>>>> 6d933837d92ba68fa3cee8f3d2ca522aec7c11b2
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: movie_db
    environment:
      - POSTGRES_USER=movienight
      - POSTGRES_PASSWORD=movienight
      - POSTGRES_DB=movienightdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movienight -d movienightdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
